# Generated by Django 4.2.4 on 2024-08-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=225)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Jobs.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.TextField()),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "job_mode",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full-Time"),
                            ("Part Time", "Part-Time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        default="FT",
                        max_length=100,
                    ),
                ),
                ("vacancies", models.PositiveIntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("Month", "Month"), ("Year", "Year")],
                        default="mnt",
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=255, null=True)),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.jobtitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(max_length=100, null=True)),
                ("designation", models.CharField(max_length=255, null=True)),
                ("salary", models.IntegerField()),
                (
                    "quit_reason",
                    models.CharField(
                        choices=[
                            ("career_advancement", "Career Advancement Opportunities"),
                            ("better_compensation", "Better Compensation and Benefits"),
                            ("work_life_balance", "Work-Life Balance"),
                            ("relocation", "Relocation"),
                            ("further_education", "Pursuing Further Education"),
                            ("new_challenges", "Seeking New Challenges"),
                            ("company_culture", "Company Culture"),
                            ("health_reasons", "Health Reasons"),
                            ("personal_reasons", "Personal Reasons"),
                            ("family_commitments", "Family Commitments"),
                            ("retirement", "Retirement"),
                            ("contract_ended", "Contract Ended"),
                            ("career_change", "Change in Career Path"),
                            ("lack_of_growth", "Lack of Professional Growth"),
                            ("work_environment", "Unsatisfactory Work Environment"),
                        ],
                        default="career_advancement",
                        max_length=255,
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Selected", "Selected"),
                            ("Rejected", "Rejected"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Jobs.jobs"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
