# Generated by Django 4.2.4 on 2024-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('job_mode', models.CharField(choices=[('Full Time', 'Full-Time'), ('Part Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='FT', max_length=100)),
                ('vacancies', models.PositiveIntegerField()),
                ('salary_type', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], default='mnt', max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
