# Generated by Django 4.2.4 on 2024-07-17 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(max_length=100, null=True, unique=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('salary', models.IntegerField()),
                ('quit_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('select', 'Select'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
