# Generated by Django 4.2.4 on 2024-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='quit_reason',
            field=models.CharField(choices=[('career_advancement', 'Career Advancement Opportunities'), ('better_compensation', 'Better Compensation and Benefits'), ('work_life_balance', 'Work-Life Balance'), ('relocation', 'Relocation'), ('further_education', 'Pursuing Further Education'), ('new_challenges', 'Seeking New Challenges'), ('company_culture', 'Company Culture'), ('health_reasons', 'Health Reasons'), ('personal_reasons', 'Personal Reasons'), ('family_commitments', 'Family Commitments'), ('retirement', 'Retirement'), ('contract_ended', 'Contract Ended'), ('career_change', 'Change in Career Path'), ('lack_of_growth', 'Lack of Professional Growth'), ('work_environment', 'Unsatisfactory Work Environment')], default='career_advancement', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('select', 'Select'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
