# Generated by Django 4.2.4 on 2024-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_alter_jobapplication_quit_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('accept', 'Select'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
