# Generated by Django 4.2.4 on 2024-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
