# Generated by Django 4.2.4 on 2024-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
