# Generated by Django 4.2.4 on 2024-07-02 06:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('country', models.CharField(choices=[('IN', 'india')], default='IN', max_length=50)),
                ('open_to_hiring', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbie', models.CharField(choices=[('traveling', 'Traveling'), ('cooking', 'Cooking'), ('reading', 'Reading'), ('gardening', 'Gardening'), ('music', 'Music'), ('gaming', 'Gaming'), ('fitness', 'Fitness'), ('photography', 'Photography'), ('writing', 'Writing'), ('dancing', 'Dancing'), ('sports', 'Sports')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('technology', 'Technology'), ('science', 'Science'), ('literature', 'Literature'), ('travel', 'Travel'), ('food', 'Food'), ('health', 'Health'), ('fitness', 'Fitness'), ('education', 'Education'), ('fashion', 'Fashion'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('politics', 'Politics'), ('environment', 'Environment'), ('sports', 'Sports'), ('history', 'History')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('ug', 'Undergraduate'), ('graduate', 'Graduate'), ('pg', 'Postgraduate'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('smoking_habit', models.BooleanField(default=False)),
                ('drinking_habit', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('images', models.ImageField(blank=True, upload_to='', verbose_name='Image/')),
                ('short_reel', models.FileField(upload_to='short_reels/')),
                ('Hobbies', models.ManyToManyField(related_name='user_activities', to='authentication.hobbies')),
                ('Interest', models.ManyToManyField(related_name='user_activities', to='authentication.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('address_line_1', models.TextField(max_length=250)),
                ('address_line_2', models.TextField(max_length=250)),
                ('address_line_3', models.TextField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IN', 'india')], default='IN', max_length=50)),
                ('pincode', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
