# Generated by Django 4.2.4 on 2024-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='age',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='qualification',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate'), ('Professional Degree', 'Professional Degree'), ('Diploma', 'Diploma'), ('Postdoctoral', 'Postdoctoral'), ('Vocational', 'Vocational')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='Hobbie',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
