# Generated by Django 4.2.4 on 2024-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_jobtitle_employment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="employe",
            field=models.CharField(
                blank=True,
                choices=[("job seeker", "JOB SEEKER"), ("employer", "EMPLOYER")],
                max_length=100,
                null=True,
            ),
        ),
    ]
