# Generated by Django 4.2.4 on 2024-07-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_employment_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.jobtitle'),
        ),
    ]
